### ISSUE TITLE
Review article 1

### ISSUE THREAD

**Issue by mbbroberg** [JnyJny/meowmeow#1]
Hey @JnyJny, edits are in! Here's part one. There are comments in `red` for review: https://opensource.com/article/19/7/structure-multi-file-c-part-1

**Comment by JnyJny** [comment]
1. Should I have the other articles referenced written to avoid the broken links? I can see it both ways, getting something out quicker with incomplete content versus something that is more polished but takes more time. I'm ok either way.

2. I'd like to change the outro of part 1 from:

```
     In part 2, we'll explore the structure of our code.
```

```
    All this prep work will pay off in part 2 where we'll explore the implementation of our toy codec.
```

Or something like that.

**Comment by mbbroberg** [comment]
@JnyJny on 1) it's always worth publishing what's done, and we can always go back and cross-link as needed. 2) Love it - Im' happy to do so.

**Comment by mbbroberg** [comment]
Done. I've adjusted any dangling links to future articles with a word change or by suggesting future articles will come (on Make and Inodes so far).

**Comment by mbbroberg** [comment]
Wdyt @JnyJny?

**Comment by JnyJny** [comment]
LGTM! But I may be biased.
