### ISSUE TITLE
Review article 2

### ISSUE THREAD

**Issue by mbbroberg** [JnyJny/meowmeow#2]
@JnyJny same game, this time here: https://opensource.com/article/19/7/structure-multi-file-c-part-2

**Comment by JnyJny** [comment]
Working on the bridge between part 1 and part 2:

In [part1](), I laid out the structure for a multi-file C program called [MeowMeow](https://github.com/jnyjny/MeowMeow.git) that implements a toy [codec](https://en.wikipedia.org/wiki/Codec). I talked about the Unix philosophy of program design, made a bunch of empty files and finally touched on what a Makefile is and what it can do for you. This article picks up where the other one left off and now I'll get to the actual implementation of our silly (but instructional) MeowMeow codec.

**Comment by mbbroberg** [comment]
Added 👍
